[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tourchain_reputation = "EDPXuESJcC2NqypbegAEdxAXVUegQpZ7wrd2Ex4AbdL6"
tourchain_escrow = "EsmThaTZhHLviAJFbpgaSTr6eCgUFGcSiboMRzb9JF6Z"
tourchain_proof = "3PfgspqxmvAh3FXUMGRPexBV7neXwLkKTPnv3gRWvPjm"

[programs.devnet]
tourchain_reputation = "EDPXuESJcC2NqypbegAEdxAXVUegQpZ7wrd2Ex4AbdL6"
tourchain_escrow = "EsmThaTZhHLviAJFbpgaSTr6eCgUFGcSiboMRzb9JF6Z"
tourchain_proof = "3PfgspqxmvAh3FXUMGRPexBV7neXwLkKTPnv3gRWvPjm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
